export type Word={id:string;english:string;translation:string;example?:string;note?:string;favorite:boolean;status:'new'|'learning'|'learned';createdAt:string;updatedAt:string;review:{repetitions:number;interval:number;nextReviewAt:string|null;lastReviewedAt:string|null}};
export type Data={version:1;words:Word[];settings:{theme:'system'|'light'|'dark';dailyGoal:number;language:'ru'|'en'};activity:Record<string,{reviews:number;sessions:number}>};
export const emptyData=():Data=>({version:1,words:[],settings:{theme:'system',dailyGoal:20,language:'ru'},activity:{}});
export const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const date=(x:unknown)=>typeof x==='string'&&Number.isFinite(Date.parse(x));
export function validateData(input:unknown):Data{const d=input as Data;if(!d||d.version!==1||!Array.isArray(d.words)||!d.settings||!d.activity||Array.isArray(d.activity))throw Error('This is not a valid WORDS version 1 backup.');const ids=new Set<string>(),names=new Set<string>();for(const w of d.words){if(!w||typeof w.id!=='string'||!w.id||typeof w.english!=='string'||!w.english.trim()||typeof w.translation!=='string'||!w.translation.trim()||typeof w.favorite!=='boolean'||!['new','learning','learned'].includes(w.status)||!date(w.createdAt)||!date(w.updatedAt)||!w.review||!Number.isInteger(w.review.repetitions)||w.review.repetitions<0||!Number.isFinite(w.review.interval)||w.review.interval<0||!(w.review.nextReviewAt===null||date(w.review.nextReviewAt))||!(w.review.lastReviewedAt===null||date(w.review.lastReviewedAt))||!(w.example===undefined||typeof w.example==='string')||!(w.note===undefined||typeof w.note==='string'))throw Error('The backup contains an invalid word.');const n=w.english.trim().toLowerCase();if(ids.has(w.id)||names.has(n))throw Error('The backup contains duplicate words.');ids.add(w.id);names.add(n);w.english=w.english.trim();w.translation=w.translation.trim();}if(d.settings.language===undefined)d.settings.language='ru';if(!['ru','en'].includes(d.settings.language))throw Error('Invalid backup settings.');if(!['system','light','dark'].includes(d.settings.theme)||!Number.isInteger(d.settings.dailyGoal)||d.settings.dailyGoal<1||d.settings.dailyGoal>1000)throw Error('Invalid backup settings.');for(const [key,a]of Object.entries(d.activity)){if(!/^\d{4}-\d{2}-\d{2}$/.test(key)||!a||!Number.isInteger(a.reviews)||a.reviews<0||!Number.isInteger(a.sessions)||a.sessions<0)throw Error('Invalid activity history.');}return d;}
const KEY='words.app.data';
export const storageService={load():{data:Data;error?:string}{try{const raw=localStorage.getItem(KEY);return {data:raw?validateData(JSON.parse(raw)):emptyData()};}catch{return {data:emptyData(),error:'Saved data could not be read. It has been left untouched. Import a valid backup or reset data to continue.'};}},save(data:Data){try{localStorage.setItem(KEY,JSON.stringify(data));}catch{throw Error('Could not save in this browser. Free storage space or allow site storage, then try again.');}},exportData(data:Data){return JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2);},importData(text:string){try{return validateData(JSON.parse(text));}catch(e){throw Error(e instanceof SyntaxError?'The file is not valid JSON.':(e as Error).message);}},merge(current:Data,incoming:Data):Data{const words=[...current.words];for(const w of incoming.words){const i=words.findIndex(x=>x.id===w.id||x.english.toLowerCase()===w.english.toLowerCase());if(i<0)words.push(w);else if(Date.parse(w.updatedAt)>Date.parse(words[i].updatedAt)){const other=words.findIndex((x,j)=>j!==i&&x.english.toLowerCase()===w.english.toLowerCase());if(other<0)words[i]=w;}}const activity={...current.activity};for(const[k,a]of Object.entries(incoming.activity)){const old=activity[k];activity[k]={reviews:Math.max(old?.reviews||0,a.reviews),sessions:Math.max(old?.sessions||0,a.sessions)};}return {...current,words,activity};}};
export function newWord(english:string,translation:string,example='',note=''):Word{const now=new Date().toISOString();return {id:crypto.randomUUID(),english:english.trim(),translation:translation.trim(),example:example.trim(),note:note.trim(),favorite:false,status:'new',createdAt:now,updatedAt:now,review:{repetitions:0,interval:0,nextReviewAt:now,lastReviewedAt:null}};}
export function streak(activity:Data['activity']){let d=new Date(),n=0;if(!activity[dayKey(d)]?.sessions)d.setDate(d.getDate()-1);while(activity[dayKey(d)]?.sessions){n++;d.setDate(d.getDate()-1);}return n;}
